title:              COMP0016 Systems Engineering
tagline:            project blog 
description:        Blog on progress of DRI map project in collaboration with IBM Doncaster, UK. 
url:                http://preston-tong25.github.io

author:
  name:             Preston
  url:              https://twitter.com/YourName
  email:            preston.tong25@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
